//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zachet4.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocenka
    {
        public int id { get; set; }
        public Nullable<int> IDPredmet { get; set; }
        public Nullable<int> IDStudent { get; set; }
        public Nullable<int> Ocenki { get; set; }
    
        public virtual Predmet Predmet { get; set; }
        public virtual Student Student { get; set; }
    }
}
