//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zachet4.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Ocenka = new HashSet<Ocenka>();
        }
    
        public int id { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> IDSpec { get; set; }
        public Nullable<int> IDGroup { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> IDForma { get; set; }
    
        public virtual Forma Forma { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocenka> Ocenka { get; set; }
        public virtual Spec Spec { get; set; }
    }
}
